config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout",  to: "devise/sessions#destroy"
    get "signup", to: "devise/registrations#new"
  end

  root 'home#index'

  get "profile" => "profile#index"
  put "profile" => "profile#update", as: "update_profile"

  authenticated :user do
    root to: "profile#index", as: :authenticated_root
  end

  resources :posts

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    authenticated_root_path
  end

protected
  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC").page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.all.order("created_at DESC").page(params[:page])
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
     redirect_to posts_path
    end
  end

private

  def all_tasks
   @tasks = current_user.posts.all
  end

  def post_params
   params.require(:post).permit(:title, :description, :url)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end

  def update
    current_user.update_attributes(user_params)
    redirect_to profile_path
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :profile_image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(page_name)
    "active" if params[:controller] == page_name
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="post col-xs-12 col-md-8 infinite-table">
    <%= render :partial => 'shared/posts', :object => @posts %>
    <div class="row pagination">
      <%= link_to_next_page(@posts, 'Next Page', :remote => true) %>
    </div>
	</div>
</div>

app/views/home/index.js.erb
// Append new data
$("<%=j render(:partial => 'shared/posts', :object => @posts) %>")
  .appendTo($(".infinite-table .posts"));

// Update pagination link
<% if @posts.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@posts, 'Next Page', :remote => true) %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>G98</title>
  <%= favicon_link_tag "apple-touch-icon", rel: "apple-touch-icon", sizes: "100x100", type: "image/png" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'sidebar' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header pull-left">
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#account" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button> -->
      <a class="navbar-brand logo" href="/">
        <%= image_tag "g98-logo"%>
      </a>

    </div>
    <div class="navbar-header pull-right">
       <ul class="nav navbar-nav pull-left upload">
         <li><%= link_to content_tag(:i, ' Upload', class: "fa fa-camera"), new_post_path %></li>
       </ul>
    </div>

  </div>
</nav>
  <div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li><%= link_to content_tag(:i, ' Hot', class: "fa fa-fire"), authenticated_root_path, class: is_active?("dashboard") %></li>
        <li><%= link_to content_tag(:i, ' Trending', class: "fa fa-star") %></li>
        <li><%= link_to content_tag(:i, ' Fresh', class: "fa fa-female") %></li>

        <% if user_signed_in? %>
          <li><%= link_to content_tag(:i, ' Account', class: "fa fa-user"), profile_path %></li>
          <li><%= link_to content_tag(:i, ' My posts', class: "fa fa-bars"), posts_path %></li>
          <li><%= link_to content_tag(:i, ' Logout', class: "fa fa-sign-out"), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to content_tag(:i, ' Login', class: "fa fa-sign-in"), login_path %></li>
        <% end %>
      </ul>
    </div>


    <div id="page-content-wrapper">
      <div class="content-header">
        <h1>
          <a id="menu-toggle" href="#" class="btn btn-default"><%= fa_icon "navicon" %></a>
          <%= yield(:title) %>
        </h1>
      </div>
    </div>
    <!-- Keep all page content within the page-content inset div! -->
    <div class="page-content inset">
      <%= yield %>
    </div>
  </div>

  <!-- Custom JavaScript for the Menu Toggle -->
  <script>

    window.onload = function() {

  var mySwiper = new Swiper('.swiper-container',{
    slidesPerView: 'auto'
  })

    }

    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
    });

    $('body').on('hidden.bs.modal', '.modal', function () {
      $(this).removeData('bs.modal');
    });
    $('body').on('hidden.bs.modal', '#confirm-delete', function () {
      $(this).remove();
    });
  </script>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>G98</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/index.html.erb
<div class="row">
  <div class="post col-xs-12 col-md-10 infinite-table">
    <%= render :partial => 'shared/posts', :object => @posts %>
    <div class="row pagination">
      <%= link_to_next_page(@posts, 'Next Page', :remote => true) %>
    </div>
	</div>
</div>

app/views/posts/index.js.erb
// Append new data
$("<%=j render(:partial => 'shared/posts', :object => @posts) %>")
  .appendTo($(".infinite-table .posts"));

// Update pagination link
<% if @posts.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@posts, 'Next Page', :remote => true) %>");
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Description</label>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Upload Image</label>
    <%= f.text_field :url, class: "form-control" %>
    <%= f.cl_image_upload(:image, :return_delete_token=>true) %>

    <div class="preview"></div>
    <div class="progress hidden">
      <div class="progress-bar" role="progressbar" aria-valuemax="100" style="width: 0%;"></div>
    </div>
  </div>

  <%= f.submit "Create Post", class: "btn btn-default" %>
<% end  %>

<%= cloudinary_js_config %>
<%= javascript_include_tag 'cloudinary-upload', 'data-turbolinks-track' => true %>

app/views/shared/_posts.html.erb
<div class="posts">
  <% @posts.each do |post|  %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-2 col-md-1">
              <%= image_tag(post.user.profile_image_url.presence || "default-profile", class: "profile-image") %>
            </div>
            <div class="col-xs-3">
              <h6><%= post.user.username %></h6>
            </div>
            <div class="col-xs-7">
              <h6 class="fa fa-clock-o pull-right"><small> &nbsp;<%= time_ago_in_words(post.created_at) %> ago</small></h6>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <%= image_tag(post.url, class: "post-image") %>
        </div>
        <div class="panel-footer">
          <div class="row post-details">
            <em class="fa fa-heart"> 10 Likes</em>
          </div>
        </div>
      </div>
  <% end %>
</div>